services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HOSTNAME=0.0.0.0
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # REMOVED the ".:/app" line here to stop the conflict
      - /app/node_modules
      - /app/.next
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
